### ISSUE TITLE
midi keyboard in list but doesn't respond to keypresses

### ISSUE THREAD

**Issue by LiftPizzas** [xenharmonic-devs/scale-workshop#269]
When I select my keyboard in the dropdown it won't play notes from it.
(Same keyboard/config works in the old SW and Reaper, and virtual keyboard plays notes.)

**Comment by frostburn** [comment]
The issue was not recording from the correct channel and sending vanishingly small MIDI velocity. See #272 for a fix that should help diagnosing issues like this in the future.
