### ISSUE TITLE
Analysis->Decimal Ratio shows non-localized decimal separators

### ISSUE THREAD

**Issue by LiftPizzas** [xenharmonic-devs/scale-workshop#270]
When language is set to US English all the other decimal points are . (period) but in this mode the decimal separator is a comma.
![image](https://user-images.githubusercontent.com/20491378/186938132-3a133dfe-bb35-4426-a91b-ccfd0f799a14.png)

![image](https://user-images.githubusercontent.com/20491378/186937872-242bfafd-6c31-4b8d-bbb4-a3ed9e3a8509.png)

**Comment by frostburn** [comment]
This is in line how cents and decimal ratios are handled and differentiated as scale lines.
We could add a few words to clarify though.

**Comment by frostburn** [comment]
Closing in favor of #284
