### ISSUE TITLE
import .scl not working when string after pitch value exists

### ISSUE THREAD

**Issue by kingemir** [xenharmonic-devs/scale-workshop#339]
https://huygens-fokker.org/scala/scl_format.html states "Anything after a valid pitch value should be ignored." (Ignored for setting up the scale itself). In practical use, people use this rule to put the name of the pitch after the pitch value. In the specifications website of the scl format (see link above), some valid examples are mentioned: 
100.0 C#
 5/4   E\

Some software even import these strings into a pitch name column, for example Lingot. 

Unfortunately, the sevish scale-workshop rejects scl files containing strings after the pitch value during import, even though these files are valid according to the format specifications.

**Comment by frostburn** [comment]
Thank you for bringing this to our attention. We'll fix Scala import in the next release.

@kingemir If you want to make sure that your .scl files are imported correctly you should attach some here so that we can use them for testing.

**Comment by kingemir** [comment]
[scl_files.zip](https://github.com/xenharmonic-devs/scale-workshop/files/10035732/scl_files.zip)
for testing
