### ISSUE TITLE
Difference in Monologue (mnlgtuns) tuning export

### ISSUE THREAD

**Issue by SeanArchibald** [xenharmonic-devs/scale-workshop#393]
The mnlgtuns file that I exported from SW2 is tuned differently to the sclkbm and tun files.

[22ed2 pentachordal decatonic LsssLsssss C261.zip](https://github.com/xenharmonic-devs/scale-workshop/files/10304820/22ed2.pentachordal.decatonic.LsssLsssss.C261.zip)

https://sevish.com/scaleworkshop/?n=22ed2%20pentachordal%20decatonic%20%28LsssLsssss%29%20C261&l=3Bm_5Bm_7Bm_9Bm_cBm_eBm_gBm_iBm_kBm_mBm&f=79.miqdhkcvh&m=1o&version=2.0.1

Exporting mnlgtuns from SW1 works as expected:

https://sevish.com/scaleworkshop1/?name=22ed2%20pentachordal%20decatonic%20(LsssLsssss)%20C261&data=3%5C22%0A5%5C22%0A7%5C22%0A9%5C22%0A12%5C22%0A14%5C22%0A16%5C22%0A18%5C22%0A20%5C22%0A22%5C22&freq=261.625565&midi=60&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=semisine&ampenv=organ

**Comment by frostburn** [comment]
The cents tables seem to be the same in both versions. Maybe the issue is in the binary conversion...
