### ISSUE TITLE
“Sort ascending” leaves the last entry in place

### ISSUE THREAD

**Issue by arseniiv** [xenharmonic-devs/scale-workshop#399]
I get that it’s probably assumed that the user always enters the period last and intends for it to stay there from the start, but how often would it be that there is, after some processing, an entry larger than the intended period somewhere inside the list?

I used this feature a couple of times yesterday to sort intervals generated by a process like Stern—Brocot tree, which generated them unordered, and was surprised until I understood today why. That’s probably a niche use, so let’s compare.

**Comment by frostburn** [comment]
This is intended behavior. The period should stay the same while sorting.
Having negative or larger-than-period intervals is an intended feature as well.

**Comment by frostburn** [comment]
@SeanArchibald any opinions on this? We could add a checkbox to sort the equave along with everything else, but this would turn a simple menu item into a full modal.

**Comment by SeanArchibald** [comment]
I think that @arseniiv's use case is not too niche at all; both use cases could be supported with a checkbox and modal as you said @frostburn. I'm all for it

**Comment by frostburn** [comment]
Default behavior changed in SW3 alpha.
