### ISSUE TITLE
Key colors on Virtual QWERTY offset one to the left on bottom row

### ISSUE THREAD

**Issue by fermata4** [xenharmonic-devs/scale-workshop#452]
Key colors on the bottom row of Virtual QWERTY are one position to the left of where they should be. When clicked, keys play the note that corresponds to their color (not in the correct position on the bottom row), but when playing on the keyboard, the keys light up and play notes as if everything is in the correct position. This may be due to the fact that there is an extra key between Z and Shift on the display that I am unable to play on my keyboard. Visual examples below:

### A 22edo isomorphic layout I created (discovered?), based on pajara[10]

![Virtual Keyboard Layout](https://github.com/xenharmonic-devs/scale-workshop/assets/102695206/fa6129b1-9550-463c-85a7-390a1e82d749)

### The same layout in Virtual QWERTY

![Virtual QWERTY Layout](https://github.com/xenharmonic-devs/scale-workshop/assets/102695206/04b1c624-051a-443a-b054-6bf510c0024b)

### When clicked, these two keys are an octave apart (correct colors, wrong position)

![Virtual QWERTY Layout When Clicked](https://github.com/xenharmonic-devs/scale-workshop/assets/102695206/568b234e-2965-4c36-8d60-49aa89cb2ab0)

### When played on the keyboard, these two keys are an octave apart (wrong colors, correct position)

![Virtual QWERTY Layout When Played](https://github.com/xenharmonic-devs/scale-workshop/assets/102695206/4ebf3ae5-e7b2-4053-842e-1ab3a073c397)

### Edit: A picture of my laptop keyboard for reference 
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/102695206/939b868e-f242-4732-afd5-07ff8d8b3c95)

**Comment by frostburn** [comment]
@fermata4 Can you provide a photo of your keyboard or a diagram of the physical layout?
If you know how to access the browser console, can you run `window.addEventListener("keydown", e => console.log(e.code));` and then go back to the main window, press every key in order and copy the resulting logs here?

**Comment by fermata4** [comment]
Thanks for reaching out, Lumi! Here's a picture of my laptop keyboard.

[image: image.png]

And here's what the console says when I press every key that plays a note
on Virtual QWERTY, from left to right, top to bottom.

Digit1
VM68:1
Digit2
VM68:1
Digit3
VM68:1
Digit4
VM68:1
Digit5
VM68:1
Digit6
VM68:1
Digit7
VM68:1
Digit8
VM68:1
Digit9
VM68:1
Digit0
VM68:1
Minus
VM68:1
Equal
VM68:1
KeyQ
VM68:1
KeyW
VM68:1
KeyE
VM68:1
KeyR
VM68:1
KeyT
VM68:1
KeyY
VM68:1
KeyU
VM68:1
KeyI
VM68:1
KeyO
VM68:1
KeyP
VM68:1
BracketLeft
VM68:1
BracketRight
VM68:1
KeyA
VM68:1
KeyS
VM68:1
KeyD
VM68:1
KeyF
VM68:1
KeyG
VM68:1
KeyH
VM68:1
KeyJ
VM68:1
KeyK
VM68:1
KeyL
VM68:1
Semicolon
VM68:1
Quote
VM68:1
Backslash
VM68:1
KeyZ
VM68:1
KeyX
VM68:1
KeyC
VM68:1
KeyV
VM68:1
KeyB
VM68:1
KeyN
VM68:1
KeyM
VM68:1
Comma
VM68:1
Period
VM68:1
Slash

Hope this helps!
fermata4

**Comment by frostburn** [comment]
@fermata4 Thank you for the logs! The image doesn't show up. Would you mind posting it directly in GitHub?

**Comment by fermata4** [comment]
I've just updated my original comment with a picture of my keyboard. Thanks!
fermata4

**Comment by frostburn** [comment]
Thanks! This should be enough to debug the issue. It's a tricky one, though. The event codes you gracefully provided are supposed to be universal, but that is far from the truth. Unfortunately I only have access to a Finnish keyboard with an extra button between *Shift* and *Z* marked with the angle brackets and a pipe symbol.

**Comment by frostburn** [comment]
Should be solved in the next release on plainsound.
