### ISSUE TITLE
Support primes up to 97 on Lattice

### ISSUE THREAD

**Issue by diegovdc** [xenharmonic-devs/scale-workshop#455]
Currently the lattice only supports primes up the 23.  Coordinates should be provided for higher primes.

However in my opinion, hardcoding coordinates (specially for non traditionally latticed primes) could prove difficult and hard to correctly. 

On the other hand a UI could be provided for users so that they can configure the coordinates however they want. This way they could modify the default coordinates, assign them to different primes, and add or remove unused primes.

A reference compass could also be a useful addition for the lattice, so that that the contextual meaning of these coordinates could be easily figured out.
             
> Scale Workshop goes up to 97. 
_Originally posted by @frostburn in https://github.com/xenharmonic-devs/scale-workshop/pull/453#discussion_r1364251062_

**Comment by frostburn** [comment]
Coordinates developed in collaboration with Scott Dakota now cover the first 72 primes in SW3 alpha:
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/ffc2143f-2668-418a-b01d-d95a20bcc918)
