### ISSUE TITLE
Allow for connection of orphan nodes when separated by more than one power along a prime axis

### ISSUE THREAD

**Issue by diegovdc** [xenharmonic-devs/scale-workshop#457]
The scale [9/8, 2/1] is disconnected. It would be nice to see an edge split into two with a small tick mark here. ![image](https://user-images.githubusercontent.com/1253499/277145521-1ac408a5-1511-4295-a52b-1e2be5d92559.png)
 
When a node has no edges based on your original algorithm, it should connect to the closest node(s) along prime(s). That way there are no floating nodes and no confusing off-prime edges either.

_Originally posted by @frostburn in https://github.com/xenharmonic-devs/scale-workshop/issues/453#issuecomment-1774143565_

**Comment by frostburn** [comment]
Scale such as those generated by stacking 5/3 should also be connected. Here you need two edges to connect prime-wise and the visualization will have corners without a visible node.

Presonally I would also prefer the whole scale to be a single connected whole so e.g. *Raga Todi* would need a long ticked edge between the two islands.

**Comment by frostburn** [comment]
Implemented in SW3 alpha.
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/4225e862-5a2b-4f68-a57b-c32b86823ee3)
