### ISSUE TITLE
Well Temperaments

### ISSUE THREAD

**Issue by 000masa000** [xenharmonic-devs/scale-workshop#477]
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/2e196b4a-b001-4d8e-a77f-19a6b959cad3)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/cb64d3d3-e783-471d-818c-4eab458e0c42)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/3dfb95cc-e7cc-4d94-93e8-eff6e9f87dcb)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/0fe95176-8dcb-426e-90c0-804bb7318e5b)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/08b74748-62c4-41a7-a776-6a45eca606b1)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/992c3d3f-b062-4389-87aa-cf9aeaa8ae32)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/e9f0bc37-7344-43bd-9c8e-5c79595481e8)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/b012ff15-cc1a-49f7-8242-36d9aa5835f3)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/8d59a2e7-1b8e-4121-b622-313fc03582d8)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/e57a9ad2-f37e-43b3-9501-3584f40fc977)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/95ddb9c1-37a4-4828-b44c-7bc07ef6b0ad)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/d38e3b0e-2efc-4917-b756-060f7ca4e56f)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/34196907/c11a0664-9255-4b05-ba3f-c62edbfb50c8)

**Comment by frostburn** [comment]
I guess now that this issue exists I could paste in the rest for archival:
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/d66c8eb8-e749-492f-b214-6e2806c0ea2d)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/be6a429f-1c09-4107-beea-b91b9b0231a2)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/eae71ca6-1889-4469-bd97-3ac53837ba75)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/a3166e64-8f7c-4dca-b358-4fec2d852b4b)
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/9aebc2b4-6f33-4803-bfa7-d34c3ceb589a)
