### ISSUE TITLE
SW3: Add note labels to virtual keyboard

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#534]
> could someone please explain how Scale Workshop's keyboard is organized? it is so difficult for me to work with without any labels

**Comment by frostburn** [comment]
Reopening for v2 backport.

**Comment by frostburn** [comment]
We're live by the way: https://sw3.lumipakkanen.com/about?version=3.0.0-beta.16

**Comment by wilckerson** [comment]
Yay! I am happy to see the feature live. 
In the following days, I should be able to finish the v2 backport. 
Thanks

**Comment by frostburn** [comment]
We're live: https://scaleworkshop.plainsound.org/?version=2.5.0
