### ISSUE TITLE
Add MOS indicators on Circle tab of Rank 2 Temperament

### ISSUE THREAD

**Issue by akselai** [xenharmonic-devs/scale-workshop#580]
Add different colored arcs (and text) on the side of the circle indicating different types of MOSes. 

Inspired by my abandoned retuner project. 
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/90088202/f354c600-e107-4c37-8a0d-dd696635cc0e)
(diatonic in ~22edo)

**Comment by frostburn** [comment]
Do you happen to have the formula for the arc start and end angles handy?

**Comment by akselai** [comment]
The endpoints where the MOS collapses or equalizes is always 1/n of an equave, so we can start from there.

**Comment by akselai** [comment]
The endpoints where the MOS collapses or equalizes is always 1/n of an equave, so we can start from there.

**Comment by frostburn** [comment]
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/6060e791-99c5-4c48-aea2-4337c27c41a8)
