### ISSUE TITLE
UI: Make checkbox gaps slightly wider

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#644]
Some of the `<label>` elements have explicit space characters in them. This doesn't look neat in template code. The gap should be controlled by CSS alone.

**Comment by frostburn** [comment]
Assigning to Marc in reference to https://github.com/xenharmonic-devs/scale-workshop/pull/642/files#r1562023627 .

**Comment by 000masa000** [comment]
copying the comment to contoinue discussion here: 
for now in main.css I replaced "select-group" with "dropdown-group" and also added "checkbox-group" to match the already existing "radio-group". Not sure but it seemed to make sense that a row of each of these HTML elements might need different spacing. Any thoughts about best way to implement this?

**Comment by 000masa000** [comment]
what class name should be given to labels that fall to the right of an input (checkbox, radio button, number) : these need a gap to the left of the text?

**Comment by frostburn** [comment]
> what class name should be given to labels that fall to the right of an input (checkbox, radio button, number) : these need a gap to the left of the text?

I don't think they need a name. CSS rules should be able to specify label elements within a checkbox container.

**Comment by frostburn** [comment]
PR was #654
