### ISSUE TITLE
Problem wirth scales created from EDO steps with n\m notation 

### ISSUE THREAD

**Issue by nylonius** [xenharmonic-devs/scale-workshop#671]
Ehkä vain en tiedä miten tämä tehdään, mutta yritän tehdä asteikon edo-askelista poistamalla joitakin askelia enkä saa SW:ia laittamaan Base frequencia ja skaalan alkua oikealle aloitussävelelle. Asteikko alkaakin listan viimeisestä sävelestä. Näin tapahtuu silloinkin kun Create Equal temperament - valikossa valitsee vain osan edo-sävelistä asteikkoon. 
Tämä on siis ongelma edo-notaation kanssa.
Senteillä voi toki muodostaa asteikon normaalisti.

Juhani

**Comment by frostburn** [comment]
Tässä esimerkki duuriasteikon generoimisesta:
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/9369cb12-5cfa-43f2-90ae-603de0e56a5e)

Sitten vielä juuritaajuus C:hen:
![image](https://github.com/xenharmonic-devs/scale-workshop/assets/1253499/8c805ad4-0962-49a1-bb1e-333d0c2b8995)

Scale Workshop seuraa Scalan esimerkkiä: Priimi-intervalli on aina implisiittinen ja yhtyy oktaaviin.

**Comment by nylonius** [comment]
Joo kiitos, oivalsin tämän heti lähetettyäni viestin mutten saanut sitä poistetuksi kysymysketjusta.Luulin ensin että 1\12 -notaatio lähtee 1:stä eikä nollasta koska mainittiin "scale degree".On toki parempi että se lähtee nollasta (tai siis että n-edon aste n = 2/1)Kiitos!JuhaniLähetetty iPadistaLumi Pakkanen ***@***.***> kirjoitti 29.4.2024 kello 13.59:﻿
Tässä esimerkki duuriasteikon generoimisesta:
image.png (view on web)
Sitten vielä juuritaajuus C:hen:
image.png (view on web)
Scale Workshop seuraa Scalan esimerkkiä: Priimi-intervalli on aina implisiittinen ja yhtyy oktaaviin.

**Comment by frostburn** [comment]
Eipä mitään. Kuka ikinä keksikään, että järjestysluvut alkavat ykkösestä, on vastuussa valtavasta määrästä turhaa hämmennystä.

Jos "ensimmäinen + ensimmäinen = ensimmäinen", niin miksei "kolmas + kolmas = kuudes" vaan viides?! Ts. terssi + terssi = kvintti.
