### ISSUE TITLE
Feature Request: provide a way to add comments inline with scale data

### ISSUE THREAD

**Issue by mfdesimone** [xenharmonic-devs/scale-workshop#688]
I'd like to be able to write text notes about the scales I'm working on. For example, I'd like to write out the MOS steps, etc. It would improve the experience of sharing or bookmarking scale URLs if we can leave reminders or clarifications that aren't easy to notice later on. Maybe this is already supported, but not documented?

I tried using an ! at the beginning of each line and that actually seems to work mostly. But the capital L doesn't get encoded into the URL correctly. For example, this was a scale that I wanted to bookmark, but the L characters came back as < characters when I opened the URL in another tab: https://sevish.com/scaleworkshop/?n=MOS%207L%205s&l=%21SEsELEsLEsLLEsLEsLL_2Bv_5Bv_7Bv_aBv_cBv_fBv_iBv_kBv_nBv_pBv_sBv_vBv_&c=-~-~-~~-~-~~&f=64&version=2.4.1

Seems that only the first L is encoded correctly as **EL**, while subsequent Ls are encoded just as **L**.
But I was able to fix the URL and bookmarking this URL leads to something that seems to work just fine:
https://sevish.com/scaleworkshop/?n=MOS%207L%205s&l=%21SEsELEsLEsELELEsELEsELEL_2Bv_5Bv_7Bv_aBv_cBv_fBv_iBv_kBv_nBv_pBv_sBv_vBv_&c=-~-~-~~-~-~~&f=64&version=2.4.1

So maybe this is a bug report instead of a feature request. Using those URLs above should illustrate for you what I'm talking about.
I hope you understand how wonderful this tool is, and what a joy it is to explore and play with it.

**Comment by frostburn** [comment]
We're currently in beta: https://sw3.lumipakkanen.com/?version=3.0.0-beta.24
Comments are straightforward:
```c
"This is your scale title."
5/4 "this is a label for the note 5/4"
// This is an inline comment
3/2 green // CSS colors supported
/*
This
is a
multiline comment.
*/
2/1
```

**Comment by frostburn** [comment]
Marking as bug for the encoding issue in SW2.

**Comment by frostburn** [comment]
Fixed in the primary deployment on plainsound: https://scaleworkshop.plainsound.org/?version=2.5.2
