### ISSUE TITLE
Realizing word throws unnecessary and wrong error on domain mismatch

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#823]
**0.5° 🍵** — _Today at 3:33 PM_

> I guess there’s a bug:
> ```js
> let [L_, M_, s_] = [9, 8, 7];
> let edo = (L_ + M_ + s_) * 4;
> realizeWord("LMsLsMLsMLsM",
>   #{L: L_\edo, M: M_\edo, s: s_\edo}, 2)
> ```
> gives an error *“Given sizes must be compatible with an explicit equave.”* despite that when I omit the equave it makes the same scale. Maybe domain mismatch or something?

**Comment by arseniiv** [comment]
So much more looking like domain mismatch then! 🎛
