### ISSUE TITLE
problems with the temper feature

### ISSUE THREAD

**Issue by MotureS** [xenharmonic-devs/scale-workshop#826]
After using the temper feature provided by the webpage, the cents changing displayed in the scale data will be retained to the nearest whole number, but when played, it will be with higher precision. When refreshing the webpage or sharing scale with URL and opening it again, the actual playing precision will also be reduced to whole numbers.

**Comment by MotureS** [comment]
the version on the sevish.com is still 2.5.7

**Comment by frostburn** [comment]
Unable to reproduce. Can you provide a link to a broken scale?

> the version on the sevish.com is still 2.5.7

 Only https://scaleworkshop.plainsound.org/ is being maintained at the moment.

**Comment by MotureS** [comment]
> Unable to reproduce. Can you provide a link to a broken scale?
> 
> > the version on the sevish.com is still 2.5.7
> 
> Only https://scaleworkshop.plainsound.org/ is being maintained at the moment.

sorry about i can only access the 2.5.7 version on sevish.com
the link was
https://sevish.com/scaleworkshop/?n=Turkish24&l=3rF3kS-S1._gFfSPS0._aF9SPS0._9F8S-S0._wFrSPS1._6F5SPS0._5F4S-S0._29F1sS-S1._4F3SPS0._rFkS-S0._19FwS-S1._1sF19SPS1._14FrSPS0._3F2S-S0._3kF29SPS1._8F5SPS0._5F3SPS0._rFgS-S1._gF9SPS1._9F5S-S0._fF8S-S0._6rF3kS-S1._4gF29SPS1._2F1SPS0.&c=~blue_red_%23BBB~blue_red_%23BBB~~red_blue_red_%23BBB~blue_red_%23BBB~blue_red_%23BBB~%23BBB&f=79.miqdhkcvh&m=1o&version=2.5.7

first i input as

https://sevish.com/scaleworkshop/?n=Turkish24&l=3rF3k_gFf_aF9_9F8_wFr_6F5_5F4_29F1s_4F3_rFk_19Fw_1sF19_14Fr_3F2_3kF29_8F5_5F3_rFg_gF9_9F5_fF8_6rF3k_4gF29_2F1&c=~blue_red_%23BBB~blue_red_%23BBB~~red_blue_red_%23BBB~blue_red_%23BBB~blue_red_%23BBB~%23BBB&f=79.miqdhkcvh&m=1o&version=2.5.7

then i tempered out 32805/32768 use comma list method, TE tuning
you can find out the difference, when something like 3/2 - 0. was playing, before and after refreshing the webpage

**Comment by MotureS** [comment]
> Unable to reproduce. Can you provide a link to a broken scale?
> 
> > the version on the sevish.com is still 2.5.7
> 
> Only https://scaleworkshop.plainsound.org/ is being maintained at the moment.

before refreshing, the 3/2 - 0. is not pure 3/2 because of tuning. but after refreshing, the 3/2 - 0. plays as pure 3/2.

**Comment by frostburn** [comment]
> sorry about i can only access the 2.5.7 version on sevish.com

I cannot update an unmaintained version. If you can't use version 3 series for some reason you'll have to fork the project and deploy a https://github.com/xenharmonic-devs/scale-workshop/tree/two .

**Comment by MotureS** [comment]
> Unable to reproduce. Can you provide a link to a broken scale?
> 
> > the version on the sevish.com is still 2.5.7
> 
> Only https://scaleworkshop.plainsound.org/ is being maintained at the moment.

you can see the image rotating very slowly in the Otonal chord in the analysis feature when impure 3/2 - 0. was playing, after refreshing, the spinning stops because the precision loss
